### ISSUE TITLE
Space Travel Kanban Board Review 

### ISSUE THREAD

**Issue by IamYunusAli** [IamYunusAli/Space-Traveler#25]
In this Project [Here](https://github.com/IamYunusAli/Space-Traveler/projects/1)

A Team of three peoples

@Piercel2022  Doing Rockets
@sharon-odhiambo Doing Missions
@IamYunusAli  Doing Dragons

**Comment by emmanuellekamwa** [comment]
**STATUS: APPROVED 🍾✔🎉**
Hello @sharon-odhiambo, @IamYunusAli and @Piercel2022 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Your linters are passing all the checks
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
